sudo: required
services:
  - docker
language: node_js
node_js:
  - "0.10"
  - "0.12"
before_install: "sudo apt-get update && sudo apt-get install libfuse-dev"
script: "npm run-script travis"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d93c390fe505596335c9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
