language: node_js
node_js:
  - "0.10"
before_install: "sudo apt-get update && sudo apt-get install libfuse-dev && sudo modprobe fuse"
script: "npm run-script travis"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
